### ISSUE TITLE
'SettingsIcon' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by furiosFast** [sparrowcode/SPSettingsIcons#5]
Hi,
when i try to create the view i get this error:
`'SettingsIcon' initializer is inaccessible due to 'internal' protection level`
<img width="1517" alt="Screenshot 2024-03-01 alle 18 23 45" src="https://github.com/sparrowcode/SettingsIconGenerator/assets/38165952/71a068be-99b4-4c48-a62a-c1c74ed02620">

**Comment by ivanvorobei** [comment]
Try `generateSettingsIcon`
